version: "3"

services:
  scraper:
    image: hicsail/gdp-flask:staging
    restart: always
    ports:
      - 5001:80
    env_file:
      - ../stack.env
  translator:
    image: hicsail/gdp-flask-translator:staging
    restart: always
    ports:
      - 5002:80
    env_file:
      - ../stack.env
  classifier:
    image: hicsail/gdp-flask-classifier:staging
    restart: always
    ports:
      - 5003:80
    env_file:
      - ../stack.env
